### ISSUE TITLE
Call functions with named arguments doesn't work

### ISSUE THREAD

**Issue by tatarincev** [lunet-io/scriban#108]
```C#
var parsedTemplate = Template.ParseLiquid("{{ math.plus value: 1 with: 2 }}");
Assert.False(parsedTemplate.HasErrors);

//{<input>(1,4) : error : Error while parsing expression statement: Invalid token found `:`. Expecting <EOL>/end of line after: <expression>}
```
I know you wrote that no so much free time to work on scriban, but nevertheless I think the community should know about this error. :)

**Comment by xoofx** [comment]
Yes, this is by design. Named arguments are a feature of scriban, not liquid here (So it is working with `Template.Parse`, not `Template.ParseLiquid`). 

This is described in [known issues for liquid support in scriban](https://github.com/lunet-io/scriban/blob/master/doc/liquid-support.md#known-issues). Liquid doesn't have a standard for arguments.
