### ISSUE TITLE
Does Scriban need to target all these frameworks?

### ISSUE THREAD

**Issue by teo-tsirpanis** [lunet-io/scriban#133]
Right now, Scriban targets:

* .NET Framework 3.5 (far too old, unsupported, does not run on anything .NET 4 cannot)
* .NET Framework 4 (unsupported, but OK if Windows XP support is needed)
* .NET Framework 4.5 (unsupported, redundant because of .NET 4 and .NET Standard 1.1, but OK because the regex timeout is a security feature)
* .NET Framework 4.7.1 (redundant because of .NET 4)
* .NET Standard 1.1
* .NET Standard 1.3 (OK, because it supports cryptographic hashing that .NET Standard 1.1 does not)
* .NET Standard 2.0 (redundant because of .NET Standard 1.3)
* .NET Core 2.0 (redundant because of .NET Standard 1.3)
* UWP (redundant because of .NET Standard 1.3, requires developers to download the entire UWP SDK)

My proposal is for Scriban to target only:

* .NET Framework 4
* .NET Framework 4.5
* .NET Standard 1.1
* .NET Standard 1.3

The proposal would simplify the project file, shrink the size of the NuGet package, make Scriban more maintainable.

**Comment by xoofx** [comment]
I would prefer to keep most configs as it is today. Reason is that `netstandard1.3` is actually not the same as `netstandard2..0` it will pull lots of packages into your project while `netstandard2.0` will not. Also `netstandard2.0` has been through [lots of trouble](https://stuartlang.uk/dotnet-framework-support-for-dotnetnet-standard-2-0/) recently, precisely because the compatibility is not as explained in their documentation.
UWP was here because 2.0 was not yet there/stable into it when Scriban was released.
NET framework 3.5 is here, well, because it has been here from the beginning... so removing it would be a breaking change. I can't tell if anyone is using it today, maybe not, but it is supported, and it doesn't cost the project a huge burden so...
So maybe 4.7.1 could be removed, as well as the UWP. For .NET Core 2.0 I'm not sure if we have the same trouble with NET Standard 2.0, but that could be ok.

So that could boil down to:

* .NET Framework 3.5
* .NET Framework 4
* .NET Framework 4.5
* .NET Standard 1.1
* .NET Standard 1.3
* .NET Standard 2.0

If you look at something like [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) it is not that far from what they are shipping today.

**Comment by teo-tsirpanis** [comment]
OK. I am working on it, as well as other changes.

BTW, the unit tests cannot run on .NET 3.5 and 4, because of asynchronous code. And the .NET 3.5 version depends on the menhir called `System.Web` for a single function (`HttpUtility.HtmlEncode`).

But there is no other problem with .NET 3.5.
