### ISSUE TITLE
Can you access methods from objects Added to a ScriptObject, rather than Imported?

### ISSUE THREAD

**Issue by deanebarker** [lunet-io/scriban#174]
I'm adding several .NET objects to a `ScriptObject`. The properties of these objects are accessible, but the methods are not.

I set a `MemberFilterDelegate` like  this:

```
templateContext.MemberFilter = m => true;
```

In theory, that should allow _every_ member in, but the methods still are not available.

In reading the doc, it seems that the default `MemberFilterDelegate` only applies to objects brought into a `ScriptObject` through `Import` rather than `Add`. Is this correct?

In a larger sense, what is the difference between `Import` and `Add`?  Why would I import something to a `ScriptObject`, rather than adding it?

Is there any way to expose methods of objects added to a `ScriptObject`?

**Comment by xoofx** [comment]
> Is there any way to expose methods of objects added to a ScriptObject?

There is no way. First because it is a safety feature of scriban (you can't accidentally release a method that a user could use) and second because "methods" in scriban don't really exist, there is no concept of "this" receiver for example. They are only "static functions" attached to an object but nothing else.

**Comment by deanebarker** [comment]
Good to know.

What is the difference between `Add` and `Import`?  Describe it to me, and I'd be happy to submit a PR for the doc clarification.

(I write [a bit](http://flyingsquirrelbook.com/)...)

**Comment by xoofx** [comment]
Import is making a copy of what the object is exposing (public fields, properties, static functions...) to the `ScriptObject`. 
Otherwise `ScriptObject` is in the end just a dictionary, so if you add a .NET object as a value of a key, it will be accessible and its properties as well (but only its properties/fields, not methods), in that case they are not imported, you are actually manipulating the same .NET object.

**Comment by xoofx** [comment]
The documentation for [Import .NET object is here](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#imports-a-net-object-instance) it is probably not clear, but the difference is at least stated 😅

**Comment by deanebarker** [comment]
I'll be honest, I still don't understand why `Add` and `Import` are two different methods. I spent some time playing around in LinqPAD -- I added and imported all sort of stuff, so I have the specifics down. But in terms of language semantics, I just think the mental model of both is "make this data available to the template," and so it's confusing that there are two different methods for this.

**Comment by xoofx** [comment]
Add adds to a dictionary directly, Import takes things from one object and copy them to the object you import to.
