### ISSUE TITLE
Null-Conditional Operator

### ISSUE THREAD

**Issue by maximiliancsuk** [lunet-io/scriban#234]
Is there anything like [C#'s Null-Conditional operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-) in Scriban? I need to access deep and dynamic object variables where any of the object references might be null:
`{{ a.b.c.d }}`
In case there is a null, the template above throws an error (rightfully so, I'd say):
> Object `a.b.c` is null. Cannot access member: a.b.c.d

What I'd like to do is the following:
`{{ a?.b?.c?.d ?? "not found" }}`
Which should output "not found", but not throw an error.

I had a peek at the code, and might try to implement it myself... anything I need to be aware of? Has anybody maybe already tried this?

I assume I need to touch [Scriban.Parsing.Lexer](https://github.com/lunet-io/scriban/blob/227388560fc730df338d8db32e882153c3b0a8df/src/Scriban/Parsing/Lexer.cs) and [Scriban.Parsing.Parser](https://github.com/lunet-io/scriban/blob/de1077e5731bdee4a246b89209d35713b5c4c9ff/src/Scriban/Parsing/Parser.cs) to get this working

**Comment by xoofx** [comment]
> Is there anything like C#'s Null-Conditional operator in Scriban? I

nope

> I had a peek at the code, and might try to implement it myself... anything I need to be aware of? Has anybody maybe already tried this?

Implementing it is fine, but doing it efficiently is usually annoying because you need to introduce temp variables, as the code `{{ a?.b?.c?.d ?? "not found" }}` would have to be translated to something like this:

```
$a_000 = a
if $a_000
    $b_000 = $a_000.b
    if $b_000
            $c_000 = $b_000.c
            if $c_000
                $c_000.d
                $found_000 = true
            end
    end
end
if !$found; "not found"; end;`
```

That would be with reusing existing code syntax tree to do that, but you could certainly introduce a new kind of `ScriptExpression` that collapse consecutive checks into a same instance. 
No need to modify the lexer, the token `?` is already handled, everything is in the Parser, and likely a new syntax node, Still, but yeah, it's non trivial work, depending on how familiar you are with parsers, it can take from 1h to several hours or more days...

Note also while working on the PR #230, I would prefer that this is done after this PR is merged back to master, as I have introduce significant changes all around.

**Comment by maximiliancsuk** [comment]
Thanks for the hints, much appreciated!

> Note also while working on the PR #230, I would prefer that this is done after this PR is merged back to master, as I have introduce significant changes all around.

I'll hold off for now and wait for the PR to be merged before I dive in myself then. :)

**Comment by xoofx** [comment]
I have added support for this in the 3.0.0 branch (alpha.8 should be out soon). I over complicated the solution in my response above, it was straightforward to implement this.
