### ISSUE TITLE
Custom Liquid tags?

### ISSUE THREAD

**Issue by limeschool** [lunet-io/scriban#245]
Heyo! Great work, loving the project.
I saw in #16 that one could implement custom functions, as in `{{ "Parameter" | Function }}`. I was wondering if one could implement a custom tag, e.g. `{% MyTag arg1="argument" … %}`? I took a look at [`liquid-support.md`](https://github.com/lunet-io/scriban/blob/master/doc/liquid-support.md) and I interpreted this to be possible, yet I'm unsure as to how to go about this.
Apologies if this questions sounds really stupid. Being a project maintainer is tough, and folks like me sure don't make it easier I suppose.

**Comment by limeschool** [comment]
I ask only because I've sort-of done this, but completely by hand, not using Scriban. Thus, my implementation of my tag is slower than I'd like it, and it uses `{! … !}` rather than the standard `{% … %}`. The tag I'm trying to implement is really simple, yet it's making a mess in my project's codebase.

**Comment by xoofx** [comment]
Scriban supports [named parameters](https://github.com/lunet-io/scriban/blob/master/doc/language.md#named-arguments) but not the Liquid variant (as explained, Liquid never standardized that part)

Liquid supports in Scriban is minimal, not meant to evolve but only to ease transition to Scriban syntax, so I would suggest to use Scriban syntax instead of Liquid.
