### ISSUE TITLE
Support for custom exception policy?

### ISSUE THREAD

**Issue by clement911** [lunet-io/scriban#32]
Hi there,

I don't have much experience with scriban yet so this may be a silly question.

The scenario is quite typical I guess. We want to allow our users to define custom html emails, and we think scriban would be a great fit.

But I was thinking about the user experience in the event that the user has a runtime error. Ideally I'd prefer the engine to be 'forgiving'.

If the user access {{ var.pty } and var doesn't exist, I would prefer to output an empty string (or output the script code verbatim, or output an error message) so that the rest of the email can still be generated. Is there a way to customise the behaviour when accessing a null property? I'd prefer not to force users to use the null-coalescing operator everywhere... And similarly if an exception is thrown from a method or any other recoverable runtime error.

Ideally, it would be also possible to 'forgive' syntax errors in a similar way, but I'm guessing this would be much harder to implement a forgiving parser...

What do you think?

**Comment by xoofx** [comment]
> If the user access {{ var.pty } and var doesn't exist, I would prefer to output an empty string (or output the script code verbatim, or output an error message) so that the rest of the email can still be generated. Is there a way to customise the behaviour when accessing a null property?

Maybe you can use the option `TemplateContext.EnableRelaxedMemberAccess = true`  Note that it only for the case where you read data. Otherwise a set will throw an error.

> Ideally, it would be also possible to 'forgive' syntax errors in a similar way, but I'm guessing this would be much harder to implement a forgiving parser...

Scriban is a somewhat a safe language, so I'm not really confident that making the language accepting whatever a user can input is a great thing for the users. This could be leading to some serious bugs, or the users could even output some sensitive data that it should not generate, going completely unnoticed for several days or weeks...etc. Discarding completely all errors is not what we should encourage.

>  And similarly if an exception is thrown from a method or any other recoverable runtime error.

"Recoverable" is context dependent, difficult to define it blindly for everything. For example, most of the builtin methods are accepting null and react accordingly to this without throwing an error, but this is because they have a defined behavior for this case. If you are exposing .NET methods and your input data can be corrupted, that's better if you control the cases where the input can be null or invalid and throws an error when it really makes sense.

**Comment by clement911** [comment]
Thanks for the quick response.
I will have to play with `TemplateContext.EnableRelaxedMemberAccess`.

Regarding safety, I didn't realize this may cause security issues. I was thinking the syntax errors could just be ignored but I see how it could be very difficult to achieve. That's fine, runtime errors are what I'm mostly interested in. Regarding functions, yes I guess I could catch exceptions and behave accordingly.
