### ISSUE TITLE
When model has Upper case properties, Render emits empty string

### ISSUE THREAD

**Issue by jhonnycano** [lunet-io/scriban#33]
When model has Upper case properties, Render emits empty string.

This is the test I've done.

```
                var template = Template.Parse("Hello {{Name}}!");
                var result = template.Render(new { Name = "World" }); // => "Hello !" 

```

**Comment by xoofx** [comment]
It is because by default it is following a ruby like syntax for member accessor by transforming them to lower case and adding a `_` previously to a change of upper case (not on the first one). So in your case only the `name` property is used. It is explained in the [Member renamer](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer)

**Comment by matbarker** [comment]
This is rather unexpected and non-obvious behaviour. I would have expected that automatic member renaming would not be the default, at least for non-liquid style parsing.

**Comment by matbarker** [comment]
The documentation linked is also incorrect, MemberRenamerDelegate expects a string to be returned, not a MemberInfo.

**Comment by xoofx** [comment]
> This is rather unexpected and non-obvious behaviour. I would have expected that automatic member renaming would not be the default, at least for non-liquid style parsing.

scriban is following how liquid templates are behaving by default. If you want to improve the documentation on this matter, PR welcome.

> The documentation linked is also incorrect, MemberRenamerDelegate expects a string to be returned, not a MemberInfo.

Indeed, will fix that. At some point, the `MemberRenamerDelegate` was taking a string instead of a `MemberInfo`.
