### ISSUE TITLE
Write documentation for the doc/runtime.md

### ISSUE THREAD

**Issue by xoofx** [lunet-io/scriban#4]

**Comment by xoofx** [comment]
@pebezo @volkanceylan I have finally made a first draft of the [runtime documentation](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md)

Let me know if you find anything not enough explained or missing...etc
Thanks!

**Comment by volkanceylan** [comment]
Hi @xoofx, 

It looks pretty good for a draft :) It would be helpful if saw this before, as it wasn't easy to understand some conventions like member renaming, but now it is clear that it is a choice to provide compability with liquid.

You might want to add some paragraph on LoopLimit / RecursionLimit (if i remember names right).

I would like to ask something, would it be possible to use a IDictionary<string, object> instead of dynamic object as model in default Template.Render method, or there is some reason that it would cause problems?

Anyway, Scriban integration to my code generator is complete, and i'm very happy with result. Here are templates i use:

https://github.com/volkanceylan/Serenity/tree/master/Serenity.CodeGenerator/Templates

Compared to older Razor generator based ones for reference they look great in my opinion:

https://github.com/volkanceylan/Serenity/tree/dotnetcore/Serenity.CodeGenerator/Views

I'm already using MarkDig, Nuglify, Scriban in Serenity and all your other projects are top notch! Thanks again.

**Comment by xoofx** [comment]
> You might want to add some paragraph on LoopLimit / RecursionLimit (if i remember names right).

Indeed.

> I would like to ask something, would it be possible to use a IDictionary<string, object> instead of dynamic object as model in default Template.Render method, or there is some reason that it would cause problems?

Dynamic objects are not mandatory. If can use also `ScriptObject` which are `Dictionary<string, object>`. But also, any `IDictionary<string, object>` can be used through an existing `ScriptObject`. So if you have something like:

```C#
var model = new ScriptObject();
Dictionary<string, object> data = ....;
model["data"]  = data;
var context = new TemplateContext();
context.PushGlobal(model);
var result = template.Render(context);
```

> I'm already using MarkDig, Nuglify, Scriban in Serenity and all your other projects are top notch! Thanks again.

Cool, thanks for the feedback.
