### ISSUE TITLE
Passing parameters to a method of an imported .Net object

### ISSUE THREAD

**Issue by peterthomastlc** [lunet-io/scriban#44]
I haven't been able to get this to work. If I have a class
`public class MyObject
    { 
        public MyObject()
        {
            HelloProperty = "hello from property!";
        }
        public string HelloProperty { get; set; }
        public string HelloMethod() { return "Hello from method!"; }
    }`

and add it to a ScriptObject with
`scriptObject1["myobject"] = new MyObject();`

then render a template with
`var template = Template.Parse("{{ myobject.hello_property }}{{ myobject.hello_method }} );`

I would expect both calls to render, but only the property call is rendered.
In fact the Scriban unit tests imply that methods are not imported with the test
`Assert.That(obj, Does.Not.ContainKey("invalid"));`
after importing an object of class
`public class MySaticObject
{
    public string Invalid()
        return null;
}`

The documentation says that
> You can easily import a .NET object instance (including its public properties and methods) into a ScriptObject

implying that I should be able to access non-static methods of imported objects, but it seems I can't.
Is this a bug?

**Comment by xoofx** [comment]
First, .NET objects when used through a ScriptObject will never expose their methods. This is for security reason.
Secondly, You can only import static methods through `ScriptObject.Import`, but the documentation was indeed not clear, sorry for that (sometimes referring to static method, but then using only the term method).

Also, there was actually a mode that allowed to import instance methods, but it was actually broken, as this is not supported
- for security reason 
- the fact that importing an object copies the properties into a `ScriptObject` but importing an instance method would let the method run on the original object (and as its properties would no longer be updated, because they are copied, it would lead to severe mismatch/bugs)
- from the fact that function are somewhat objects in scriban, so you can copy them from one object to another object, so it would lead to weird behavior again

So as part of commit 4c0d6d7 I have fully remove support for instance methods.

Scriban supports only static functions or delegates (that can still capture a "this"  script object, but you have to be careful then)

**Comment by peterthomastlc** [comment]
Thanks for the clarification and the update.
It's a shame though - my usage is for purely read-only access to the imported objects, so the fact that properties are copies would make no difference.
The security argument is think is null and void as it can be circumvented with delegates.
I guess I'll have to go the delegate route with 'this' parameters.

**Comment by xoofx** [comment]
> The security argument is think is null and void as it can be circumvented with delegates.

Not exactly, because you decide to expose which delegate you want, and you have to do this explicitly. You can't leak accidentally a method on an object that should not be exposed. But if you want unrestricted .NET access, Razor might be a better choice.

**Comment by anastasiiakuzina-payroc** [comment]
@xoofx  I think documentation is still missleading 

`var scriptObject1 = new ScriptObject();
// Notice: MyObject is not imported but accessible through
// the variable myobject
scriptObject1["myobject"] = new MyObject();

var context = new TemplateContext();
context.PushGlobal(scriptObject1);

var template = Template.Parse("This is Hello: `{{myobject.hello}}`");
var result = template.Render(context);

// Prints This is MyFunctions.Hello: `hello from method!`
Console.WriteLine(result);`

from https://github.com/scriban/scriban/blob/master/doc/runtime.md#accessing-a-net-object makes me read it as I can import the object and call it via myobjcect.hello but it is not possible based on this thread, is that correct? This sample also referes to the object example but there is no example of the MyObject with the method.

**Comment by xoofx** [comment]
> from https://github.com/scriban/scriban/blob/master/doc/runtime.md#accessing-a-net-object makes me read it as I can import the object and call it via myobjcect.hello but it is not possible based on this thread, is that correct? This sample also referes to the object example but there is no example of the MyObject with the method.

There is a big statement in the link:

> **_Note that for security reason, only the properties of .NET objects accessed through another ScriptObject are made accessible from a Template. Methods and static methods are not automatically imported._**

So, I don't think that the documentation is misleading. It's pretty clear.
