### ISSUE TITLE
Passing in DateTimeOffset throws exception using to_string

### ISSUE THREAD

**Issue by andymac4182** [lunet-io/scriban#50]
```csharp
var template = Template.Parse("{{EventDate | date.to_string '%A, %e %B %Y'}} Test");

template.Render(new { EventDate = DateTimeOffset.MaxValue}, member => member.Name).Dump();
```

Throws the exception 
```
Unable to convert parameter #0 of type `System.DateTimeOffset` to type `System.Nullable`1[System.DateTime]`
--
```

Not sure where to look but having a look through the code currently

**Comment by xoofx** [comment]
Scriban supports `DateTime` object but not `DateTimeOffset`. If you want to pass a `DateTimeOffset` object to a `date.to_string` you need to access its datetime (e.g:  `"{{EventDate.DateTime | date.to_string '%A, %e %B %Y'}} Test"`

**Comment by farlock85** [comment]
For future readers, I couldn't get this to work, it fails silently, this does work:
```{{EventDate.date_time | date.to_string '%A, %e %B %Y'}} Test```

**Comment by willemduncan** [comment]
That's because of the [MemberRenamer](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer).

But I'm really here to ask why there is no support for `DateTimeOffset`? It is a useful part of the `System` namespace, and having to use the above posted workaround is cumbersome. 

Please consider adding support. In case, would you accept a PR adding this functionality?
