### ISSUE TITLE
Support of .net 2.1 Span<T> to speed Scriban rendering

### ISSUE THREAD

**Issue by epicsoft** [lunet-io/scriban#82]
Do you have any plans to produce a .net core 2.1 optimized (Span<T>, Memory<T>) version of Scriban? 
Thank you for the great library!

**Comment by xoofx** [comment]
Not sure it would make sense. The main optimization that scriban would benefit is to precompile the scripts to C#. We could maybe also get some gain of using StringUtf8 instead, maybe improve the parsing of primitives... but otherwise, for Span/Memory I don't see where Span/Memory could be used. We are already using string slices for the raw part of the script (the not scripted part), equivalent to a Span (but at least, we can use it inside a class unlike span)
Have you seen anything particular in the codebase where Span would have a significant impact?

**Comment by epicsoft** [comment]
Ok. Thank you for the answer. I did not look at the source code - tt was just a general assumption.
